KVA-31 Sprint 5 web api
YP-KVAS/Rover-game pull request #10
Opened 2023-04-06 13:50 UTC by KateDriga

### Какую задачу решаем
Добавьте минимум одно Web API.

### Скриншоты/видяшка (если есть)

https://user-images.githubusercontent.com/114503332/230397577-c3fd3d2e-36a7-4b0d-a110-f02561277d8a.mp4

### Описание
Fullscreen для страницы с игрой
Изначально хотела вынести эту логику в отдельный хук, но для совсем универсального решения необходим стейт, а для игры это не подходит поскольку при переключении на полноэкранный режим в середине игры произойдет перерендер и сбросится прогресс. Кроме того, fullscreen  в других частях приложения не нужен.

2023-04-06 18:04 UTC, Erebuz requested changes
Надо наверное поправить размер игры при фуллскрине. А то толку от него никакого, кроме того что он формально подключен)

2023-04-06 18:04 UTC, Erebuz commented on packages/client/src/components/GameField/GameField.module.scss
> +}
А мы можем отмасштабировать игру? А то фуллскрин то есть, а смысла в нем нету - игра то не увеличивается)
Например сделать transform: scale, или исользвать zoom. Не знаю, сработает ли с канвасом.

2023-04-07 10:05 UTC, KateDriga commented on packages/client/src/components/GameField/GameField.module.scss
> +}
Вообще хорошая идея, я на ноутбуке проверяла, а там игра и так почти на весь экран. Добавила media-screen (desktop first) и transform-scale для игры (zoom на MDN не советуют использовать). При этом, для небольших экранов (меньше 1200) даже уменьшила размер поля, а увеличение только для экранов больше 1600. Возможно, коэффициенты придется пересмотреть, когда будет готова панелька с информацией по прогрессу в игре (таймеры, жизни).

2023-04-07 10:28 UTC, KateDriga commented
Последний коммит не относится к задаче, подправила картинки для 2-х машинок (они были неверного размера).

2023-04-07 12:30 UTC, Erebuz approved these changes

2023-04-08 16:40 UTC, SerghAl approved these changes
Все чисто и понятно написано! Было то же предложение, что и у Димы, но повторяться не буду)

2023-04-09 10:18 UTC, merged