Sprint 5 game triggers
YP-KVAS/Rover-game pull request #11
Opened 2023-04-06 17:01 UTC by Erebuz

## Классы Triggers

Для реализации механик игры создан класс BaseTrigger. Идея в том, что на карте есть динамические объекты, которые реагируют на взаимодействие с ровером, и вызывают определенные функции.

Для создания триггера необходимо прописать в level-information начальные состояния объектов Триггер: 
- ID
- положение на карте
- класс триггера (создается как наследник от BaseTrigger)
- картинка
- начальное состояние
- функцию с логикой включения/отключения других триггеров.

ID триггера должно быть уникальным внутри уровня для того. чтобы можно было включать или отключать его по другим событиям. Для этого в функции logic следует вызвать соответствующий статический метод класса BaseTrigger.

## Класс GameManager

Кроме того, создан общий класс GameManager, инстанс которого хранит данные о игровом процессе (текущий уровень, набранные очки, в перспективе здоровье и все такое).

На данный момент в класс имплементирована смена уровней, а так же все внутриигровые события на уровне метовод-заглушек.

### Скриншоты/видяшка

https://user-images.githubusercontent.com/77618433/230446296-9d0e7a5e-25e4-409a-b101-2076dbc55c1b.mp4

### TBD (если есть)

2023-04-08 13:08 UTC, KateDriga approved these changes
Вроде все работает)
Отличная работа, игра уже начинает приобретать законченный вид

2023-04-08 20:05 UTC, Erebuz commented on packages/client/src/components/game-field/GameField.module.scss
> +.gameWrapper {}
Не, просто думал придется враппер стилизовать для отображения, а в итоге не пришлось)

2023-04-08 20:07 UTC, Erebuz commented on packages/client/src/game-engine/game-objects/base-classes/BaseTrigger.ts
> +  }
Да, помогло, спасибо. Исправил.

2023-04-10 20:09 UTC, SerghAl approved these changes
Все очень понятно написано. Единственное, что хочется - более подробную документацию с примерами как добавлять собственные тригеры и для каких игровых механик подойдет данный функционал. Пока изучал код - разобрался, и понятно, что для нашего проекта это будет излишне))

2023-04-10 20:09 UTC, SerghAl commented on packages/client/src/game-engine/GameManager.ts
> +        this._immunity = false
Как вариант, можно добавить мигание ровера во время иммунитета, чтобы было понятнее, на какое время исчезает урон

2023-04-10 20:54 UTC, Erebuz commented on packages/client/src/game-engine/GameManager.ts
> +        this._immunity = false
Да, мигание неплохая мысль. Не подумал, добавлю.

Насчет возможных механик - в сущности, да, класс базового триггера не реализует никакой игровой механики, а делает ровно то, что написано - создает объект, который при приближении ровера вызывает функцию и исчезает. 
Что это за функция, какие "ниточки" она будет дергать - описано уже в наследниках. В случае с базовой механикой - это вызов функции начисления очков. Но в теории может быть что угодно, от смены уровня или окончания игры, до получения урона хп (условная "мина"), потери управления ("масло"), и тд и тп.
Единственное что тут не очень очевидно - что есть еще функция logic в TriggerInfo. По задумке она существует, чтобы можно было по срабатыванию одного триггера вызывать включение и отключение других триггеров. То есть это информация, которая формирует логику игрового уровня - нельзя доставить груз, пока он еще не получен, и тп.

2023-04-12 09:57 UTC, Tsvetkraft requested changes
Пара стилистических мелочей

2023-04-12 09:57 UTC, Tsvetkraft commented on packages/client/src/game-engine/game-objects/Triggers.ts
> +    gameMap: Array<Array<Array<number>>>,
Тоже по мелочи стилистическое, почему не `number[][][]`? короче же, и без вложенности

2023-04-12 09:57 UTC, Tsvetkraft commented on packages/client/src/game-engine/level-information.ts
>    gameMap: Array<Array<Array<number>>>
Непоследовательно массивы называете, то через шаблон, то через встроенный синтаксис. Лучше через встроенный синтаксис.

2023-04-12 18:42 UTC, AndreyTsvetkov approved these changes

2023-04-12 19:21 UTC, merged