Sprint 5 forms
YP-KVAS/Rover-game pull request #2
Opened 2023-03-23 19:53 UTC by SerghAl

### Какую задачу решаем
Реализовал компонент формы, инпутов и страницы регистрации.
В utils добавил модуль validation с правилами валидации и объектами ошибок для каждого поля форм
Добавил css переменны (на обсуждение)

В работе использовал React Hook Form

### Скриншоты/видяшка (если есть)
После заполнения имени нажал Enter из-за чего произошла отправка формы и выполнение валидации с появлением ошибок в заполнении полей

https://user-images.githubusercontent.com/25511420/227335075-0ab039f2-5a95-4bee-99f4-8e26804f7c79.mp4

### TBD (если есть)

2023-03-24 04:09 UTC, SerghAl commented on packages/client/src/components/FormInput/FormInput.tsx
> +      )}
Спасибо за совет, поэкспериментирую с вариантами

2023-03-24 12:35 UTC, KateDriga requested changes

2023-03-24 12:35 UTC, KateDriga commented on packages/client/src/components/Button/Button.tsx
> +      onClick={clickHandler ? clickHandler : undefined}
тут не нужен undefined, лучше просто `onClick={clickHandler}`

2023-03-24 12:35 UTC, KateDriga commented on packages/client/src/App.tsx
>  import './App.css'
Здесь, а также для стилей всех остальных компонентов, я бы использовала CSS модули.
Для этого нужно назвать файл со стилями `some-awesome-name.module.css|scss`.
Импорт будет выглядеть так: `import styles from './App.css'` (вместо styles можно использовать другое имя, естественно). И использование в теге: `className={styles.className}`.

Это позволит избежать конфликтов в названии классов, а также опечаток в названии классов, т.к. IDE содержит подсказки с их названиями.

2023-03-24 12:35 UTC, KateDriga commented on packages/client/src/components/FormInput/FormInput.tsx
> +      />
Для инпутов лучше дополнительно указать соответствующий `type`. Например, `text`, `email`, `password`, `tel`. `text` - значение по умолчанию.
Это позволит открывать специальные клавиатуры, если они поддерживаются (например, для tel открывается клавиатура с цифрами на мобильных устройствах), скрывать пароль и т.д.

2023-03-24 12:35 UTC, KateDriga commented on packages/client/src/pages/Registration/Registration.tsx
> +          errorsMsgs={passwordErrors}></FormInput>
На странице регистрации лучше добавить еще одно поле `Подтвердите пароль`

2023-03-24 12:35 UTC, KateDriga commented on packages/client/src/index.css
Получилась очень красивая страница :)

2023-03-24 12:47 UTC, KateDriga commented on packages/client/src/pages/Registration/Registration.tsx
> +  }
Нам нужно будет синхронизоваться с типами TS, т.к. при отправке запросов (задача про fetch) я создавала интерфейс с точно такой же структурой.
Нужно будет вынести куда-нибудь общие типы, например,  в `utils/types`, назвать их более универсально (у меня название соответствует целям моей задачи, у тебя - твоей), а потом переиспользовать в проекте.
(это не замечание, просто нужно учесть при мердже)

2023-03-24 16:53 UTC, Alena-0046 approved these changes

2023-03-24 17:24 UTC, KateDriga approved these changes

2023-03-26 13:25 UTC, SerghAl commented on packages/client/src/components/Button/Button.tsx
> +      onClick={clickHandler ? clickHandler : undefined}
Спасибо, поправил

2023-03-26 13:25 UTC, SerghAl commented on packages/client/src/App.tsx
>  import './App.css'
Согласен, поправил

2023-03-26 13:26 UTC, SerghAl commented on packages/client/src/pages/Registration/Registration.tsx
> +          errorsMsgs={passwordErrors}></FormInput>
Согласен, добавил. Просто в Swagger нет этого поле как обязательно, но для проверки на фронте не помешает

2023-03-26 13:26 UTC, SerghAl commented on packages/client/src/components/FormInput/FormInput.tsx
> +      />
Добавил

2023-03-26 13:28 UTC, SerghAl commented on packages/client/src/pages/Registration/Registration.tsx
> +  }
Да, отличная идея. Как я понял, для объявления типов используются .d.ts файлы. Если просто ts использовать, то приходится постоянно импортировать типы в файл. Немного поменял структуру проекта, вынес типы в @types

2023-03-26 15:24 UTC, SerghAl commented on packages/client/src/components/FormInput/FormInput.tsx
> +      )}
Вынес отображение ошибок сбоку от формы, чтобы не возникало изменение высоты формы. Размеры эмпирически подобрал, но думаю для этой задачи подойдет и такое решение)

2023-03-26 15:25 UTC, SerghAl commented on packages/client/src/components/FormInput/FormInput.tsx
> +      )}
Видео поменял на актуальное отображение

2023-03-26 19:53 UTC, AndreyTsvetkov requested changes
Команда отлично провела ревью выше, только это могу дополнить.

2023-03-26 19:53 UTC, AndreyTsvetkov commented on packages/client/@types/Button.d.ts
Боюсь, тут произошло некоторое недопонимание. Файлы деклараций – это способ интегрировать в проект написанные не на TypeScript библиотеки, которые хочется использовать, но они лишены типизации. Либо добавить к написанному изначально на JS проекте типизацию внешних контрактов по-быстрому.

Нормальный "наш" код, написанный сразу на TS никак не предполагает наличия файлов `.d.ts`. 

Далее, группировка "типы" тоже семантически неверна. Каждый тип относится к тому или иному модулю, и должен там и находиться. Контракт пропсов кнопки - в файле этой кнопки. Инпута формы - соответственно. 

Набор контрактов вызова сервера соотвественно должен лежать рядом с самим сервисом, который эти вызовы осуществляет, и т.п.

2023-03-26 19:53 UTC, AndreyTsvetkov commented on packages/client/src/components/Button/Button.tsx
> +}: TButton) => {
я бы назвал это ButtonProps, такой негласный стандарт де-факто

2023-03-26 19:53 UTC, AndreyTsvetkov commented on packages/client/src/components/FormInput/FormInput.tsx
> +}: FormInputProps) => {
как вот тут, например

2023-03-26 23:26 UTC, Erebuz commented on packages/client/src/components/FormInput/FormInput.module.css
> +}
Небольшой недостаток разметки - если в ошибке мало текста, то она размещается как бы "в стороне" от поля.
![image](https://user-images.githubusercontent.com/77618433/227811051-385a5230-87b7-4d91-af7d-1a9ba909a982.png)

Надо либо сделать ширину блока с ошибкой постоянным, либо чтобы она появлялась не относительно левого края, а относительно правого

2023-03-26 23:26 UTC, Erebuz commented on package.json
> +    "babel-jest": "^29.5.0"
Возможно стоит сразу установить sass, и использовать scss, раз мы вроде бы с этим определились.
(Для этого надо поставить sass, и в jest.confg.js добавить 
```moduleNameMapper: {
    '\\.(css|scss)$': 'babel-jest',
  },
  ```
Раз уж все равно дорабатывать:)

2023-03-27 11:51 UTC, SerghAl commented on packages/client/@types/Button.d.ts
Спасибо за объяснение! Действительно недопонял их предназначение

2023-03-28 09:54 UTC, pushka-pashka commented on packages/client/src/App.tsx
> +      <Registration></Registration>
Можно просто `<Registration />`

2023-03-28 10:09 UTC, SerghAl commented on package.json
> +    "babel-jest": "^29.5.0"
Ок, не против

2023-03-28 10:09 UTC, SerghAl commented on packages/client/src/App.tsx
> +      <Registration></Registration>
Хорошо, думаю читаемость несколько улучшится

2023-03-28 10:10 UTC, SerghAl commented on packages/client/src/components/FormInput/FormInput.module.css
> +}
Хорошо, поправил

2023-03-31 11:37 UTC, pushka-pashka reviewed
Критичных замечаний нет. Нужно подтянуть свежие изменения в ветке sprint_5, в ней уже есть часть твоего кода, и разрулить конфликты.

2023-03-31 11:37 UTC, pushka-pashka commented on package.json
> +    "sass": "^1.60.0"
Эти зависимости должны быть в client/package.json
Дима уже влил их в своем PR. Подтяни изменения из ветки sprint_5.
Поэтому этот код можно убрать.

2023-03-31 11:37 UTC, pushka-pashka commented on packages/client/jest.config.js
Это тоже уже есть в ветке  sprint_5

2023-03-31 11:37 UTC, pushka-pashka commented on packages/client/src/App.test.tsx
> +  expect(screen.getByText(appContent)).not.toBeDefined()
А зачем ты меняешь тест? он падает и не дает закоммитить?

2023-03-31 11:37 UTC, pushka-pashka commented on packages/client/src/App.test.tsx
> +  expect(screen.getByText(appContent)).not.toBeDefined()
Это тоже уже есть в ветке sprint_5, можно убрать этот изменение.

2023-03-31 11:37 UTC, pushka-pashka commented on packages/client/src/App.tsx
> +      <Registration />
Это скорее для разработки. Стоит подтянуть ПР с роутером и сделать так, чтобы по по адресу http://localhost:3000/registration отдавалась Registration

2023-03-31 11:37 UTC, pushka-pashka commented on packages/client/src/components/Form/Form.tsx
> +  children: JSX.Element[]
Это не хочешь вынести в FormProps ?

2023-03-31 11:37 UTC, pushka-pashka commented on packages/client/src/components/FormInput/FormInput.module.scss
> +.input {
Давай стили этого класса поднимем в самый верх, перед `.input--container`

2023-03-31 11:37 UTC, pushka-pashka commented on packages/client/src/components/FormInput/FormInput.tsx
> +
лишняя пустая строка

2023-03-31 11:37 UTC, pushka-pashka commented on packages/client/src/main.tsx
Это тоже уже есть в ветке sprint_5

2023-04-04 12:46 UTC, pushka-pashka commented on packages/client/src/components/FormInput/FormInput.module.scss
> +.input--container {
Давай нижние подчеркивания использовать для консистентности. И так автодополнение будет работать в ts файлах при обращении к классу: style.input__container

2023-04-05 13:10 UTC, Tsvetkraft approved these changes

2023-04-05 13:11 UTC, Tsvetkraft approved these changes

2023-04-06 17:50 UTC, merged