Sprint 8 forum api
YP-KVAS/Rover-game pull request #25
Opened 2023-05-02 13:47 UTC by KateDriga

### Какую задачу решаем
[Продумать и реализовать API форума](https://linear.app/kvas/issue/KVA-46/produmat-i-realizovat-api-foruma)
[Поддержать API форума на клиенте](https://linear.app/kvas/issue/KVA-53/podderzhat-api-foruma-na-kliente)

### Краткое описание
Форум состоит из следующих сущностей:
- Категория (определяется администратором, клиент не может их изменить, но может создавать темы внутри каждой категории), включает в себя `id`, `name`, `topicCount`.
- Топик или тема, состоит из `id`, `name`, `category_id`,  `user_id`, `createdAt`, `updatedAt`.
- Комментарий, включает `id`, `message`,  `parent_comment_id`,  `user_id`, `topic_id`, `createdAt`, `updatedAt`.

Также в базу добавлены таблицы roles (я пока добавляю 2 роли - обычный пользователь или администратор) и users. Id в таблице users соответствует id пользователя в базе практикума.

В базе есть небольшая денормализация (поле topicCount в категории). Это расчетное значение, но оно хранится в базе, т.к. страница с категориями наиболее посещаемая, категорий немного, добавление топиков происходит значительно реже, чем получение данных по ним, также хотелось попробовать написать хотя бы одну транзакцию)

Для форума реализованы следующие роуты:
- /forum - список всех категорий
- /forum/:categoryId - список топиков, относящихся к categoryId
- /forum/:categoryId/:topicId - список комментариев, относящихся к topicId

На странице комментариев сначала загружаются все верхнеуровневые комментарии.
Комментарии к комментариям подгружаются по parent_comment_id.

Для удобства топики и комментарии сохраняются в стор в виде объекта, в котором ключом является category_id, а для комментариев parent_comment_id. Также в сторе хранятся только комментарии, относящиеся к текущему топику. Если перейти на другую страницу, то комментарии очищаются.

Категории может добавить только администратор, на странице с топиками реализован бесконечный скролл и поиск по названию темы,  на странице комментариев реализована пагинация. Отредактировать или удалить тему/комментарий может только их автор.

Для поля сообщения использована библиотека [ProseMirror](https://prosemirror.net/). Я глубоко не вникала в ее возможности (в рамках данного проекта это не нужно), использована самая простая настройка из [базового примера](https://prosemirror.net/examples/basic/).

Для сервера реализована стандартная структура - 
`models` (описание сущностей и связей), 
`repositories` (взаимодействие с бд), 
`services` (промежуточный слой между контроллером и репозиторием, бизнес логика), 
`controllers` (обработка запросов, результаты), 
`middlewares` (проверка входных данных), 
`router` (прописаны маршруты).

Документацию (Swagger) можно посмотреть локально http://localhost:3001/api-docs/
В дальнейшем нужно будет добавить в нее авторизацию.

Дополнительно добавила `docker-compose` для postgres. Для docker-compose есть отдельная задача, это временный файл для удобства запуска проекта (содержит только базовые вещи, не включает healthchecks, pgAdmin и т.д).

В файле init-db.sql можно прописать значения для предварительного заполнения базы данных. Для того, чтобы протестировать роль администратора, нужно для таблицы users заменить `1234` на id пользователя, с которым будете проверять.

### Как запустить
1. Поскольку в настоящий момент у нас не реализован SSR, то нет возможности получить куки пользователя. Сейчас можно скопировать их из браузера и прописать вручную в файле `/server/src/utils/yandex-api/auth-api.ts`
Но все необходимые заготовки (в т.ч. http-proxy-middleware) для авторизации я добавила.
<img src="https://user-images.githubusercontent.com/114503332/235659608-6fc945bd-e76c-43e3-8259-acc68aacd0e4.png" width="400">

2. Заменить в `/server/db-scripts/init-db.sql` `1234` на id своего пользователя (необязательно, но позволит производить действия с категориями)
3. Выполнить `docker-compose up -d` (если очень хочется, то, конечно, можно установить Postgres и запускать без докера)
4. Дождаться пока развернется база внутри контейнера, запустить client и server

Volume с базой лежит в директории pgdata, если ее удалить, то при следующем запуске база будет проинициализирована начальными значениями из  init-db.sql

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/114503332/235657779-34e95bb1-0d5e-40ee-a96c-b68858d18da5.png)

https://user-images.githubusercontent.com/114503332/235658569-1d253cb8-5978-4fd9-b50f-e3cef305e9a3.mp4

https://user-images.githubusercontent.com/114503332/235658623-eb9c76bf-ec19-4788-b7f1-2ab70e66d0cc.mp4

2023-05-11 22:52 UTC, Erebuz approved these changes
Проблем навскидку не нашел, но честно говоря, очень сложно такой объем проверять) Стоило бы разбить на отдельные задачи-ветки.

Но, конечно, объем работы проделан - мое почтение:)

2023-05-11 22:52 UTC, Erebuz commented on packages/server/docker-compose.yml
> +
А почему не в корне проекта, где уже есть файл на эту тему? Я последний раз запускал докер как раз с ним, и у меня случился конфликт, не сразу понял, что вообще за беда, и почему два контейнера с БД:)

2023-05-12 10:49 UTC, KateDriga commented on packages/server/docker-compose.yml
> +
Просто я изначально не планировала что-то делать с docker-compose. 
Исправила, конечно, файл должен быть в корне проекта, удалила docker-compose из директории с сервером.

2023-05-16 07:29 UTC, Tsvetkraft requested changes
Огромная работа проделана, и высокого качества. Ряд замечаний выше.

2023-05-18 08:08 UTC, KateDriga commented on db-scripts/init-db.sql
> +
Для остальных таблиц не нужны начальные данные. На самом деле даже для категорий их было делать необязательно, т.к. на UI предусмотрена возможность их добавления администратором, но решила все-таки их добавить в `init-db` скрипт. Темы и комментарии уже добавляют пользователи. Т.е. по умолчанию форум пустой, без тем и комментариев. В таблицу `users` новые пользователи попадают, когда пытаемся в первый раз получить их роль (если пользователя нет, то добавляем его с ролью `regular`)

Не совсем понимаю, что сейчас нужно дополнительно добавить в данный скрипт. Должен быть уже форум с категориями, темами и предзаполненными комментариями от разных пользователей?

2023-05-18 08:09 UTC, KateDriga commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +  options: Array<OptionProps>
Пока не стала исправлять данный код. Мне казалось, что разницы между `OptionProps[]` и `Array<OptionProps>` нет, можно использовать любой вариант. В целом, в проекте почти везде у нас встречается запись через `Array`, есть несколько мест, где `[]`, но их существенно меньше.
Не совсем понимаю, почему нужно исправлять это в компоненте `Dropdown`. Или нужно править вообще по всему проекту?

2023-05-18 08:14 UTC, KateDriga commented on packages/client/src/components/LeaderboardTable/LeaderboardTable.tsx
> +      value.data.login ??
Я уже прокомментировала данное замечание в [PR к 7-ому спринту](https://github.com/YP-KVAS/Rover-game/pull/28). 
Данный кусок кода встречается один раз. В том ПР изменился базовый URL, в данном ПР изменяла стили для прокрутки и вынесла их отдельно, чтобы можно было применять в разных компонентах. Видимо до этого верстка лидерборда коммитилась игнорируя прекоммит хук, поэтому попали и данные изменения, т.к. строка была слишком длинная.

Но этот код встречается один раз. Я поменяла базовую ветку, в которую происходит мердж (вместо `dev` сейчас `sprint_7-ssr_router_redux`), теперь данного куска кода нет в измененных файлах.

Лидербордом продолжает заниматься Алёна @Alena-0046 .
Поэтому мне кажется, что сейчас в рамках форума не нужно тут ничего менять.

2023-05-18 08:15 UTC, KateDriga commented on packages/client/src/hooks/useDebounce.ts
> +export const useDebounce = (value: string, delay = 500) => {
Да, работает как и ожидалось. Отправляем запрос к апи только после того, как пользователь перестанет печатать, т.е. пройдет 500ms (или другое значение `delay`) после ввода. Когда значение меняется в пределах `delay`, то таймер обновляется (очищается и стартует заново). Т.е. хук возвращает только последнее значение.

2023-05-18 08:16 UTC, KateDriga commented on packages/client/src/utils/types/forum.ts
> +interface GetForumItems {
Названия переименовала. `IGetForumItemsBaseQuery` - общий интерфейс, уже от него наследуются запросы для топиков (`IGetForumTopicsQuery`) и комментариев (`IGetForumCommentsQuery`).

2023-05-18 12:15 UTC, Tsvetkraft requested changes

2023-05-18 12:15 UTC, Tsvetkraft commented on db-scripts/init-db.sql
> +
Нет, про начальные данные нет вопроса, темы и комментарии пусть пустые на старте. Но таблички-то для них где, вот про это я.  Категории, роли и пользователи я вижу CREATE TABLE. А откуда возьмутся таблички для прочего?

2023-05-18 12:15 UTC, Tsvetkraft commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +  options: Array<OptionProps>
Да, верно, это не к локальному месту, а скорее везде. 
Запись с Array<T>:

1. более громоздка, глаз при чтении дергается, 
2. не поддерживает ключевое слово `readonly` 

```
let err2: readonly Array<boolean>; // error!    
let okay: readonly boolean[]; // works fine
```

3. не поддерживает кортежи на основе массивов [int, string]

Главным образом, конечно, п. 1.

2023-05-18 16:07 UTC, KateDriga commented on db-scripts/init-db.sql
> +
Sequelize на основе моделей создает таблицы автоматически, если их нет.
[Документация](https://sequelize.org/docs/v6/core-concepts/model-basics/#model-synchronization)

У меня в функции `dbConnect` происходит синхронизация и создание отсутствующих таблиц с топиками и комментариями за счет выполнения `sequelize.sync()`
[Файл с функцией dbConnect](https://github.com/YP-KVAS/Rover-game/blob/sprint_8_forum_api/packages/server/db.ts)

2023-05-18 16:08 UTC, KateDriga commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +  options: Array<OptionProps>
1. Тут скорее дело вкуса или привычки, если названия более длинные и составные, то `[]` в самом конце можно и не заметить, а вот запись с `Array` сразу бросается в глаза. 
2. Можно использовать `ReadonlyArray`. Но тут соглашусь, будет менее читабельно, если на соседней строчке запись с readonly.

Прошлась по всему проекту и заменила `Array` на `[]`.

2023-05-25 06:35 UTC, merged