KVA-37: Sprint 7 base ssr
YP-KVAS/Rover-game pull request #26
Opened 2023-05-05 15:50 UTC by SerghAl

Настроил Express для Server Side Rendering (без Redux, просто отдавать React-страничку).

Для сборки SSR из корня проекта нужно выполнить команду yarn ssr

При реализации, часть кода, где используется браузерное API вызывало ошибки, поэтому в некоторых местах использовалась проверка на то, что код выполняется на стороне сервера `import.meta.env.SSR`:

1. В App.tsx при использовании `localStorage` при установке темы приложения
2. В router/index.tsx при выборе `createMemoryRouter` и `createBrowserRouter`
3. В pages/GamePage/GamePage.tsx при использовании `gameManager `и `GameField`, так как внутри они вызывают конструктор `Image `, спрятанный в `game-engine/game-images.ts`, которого также нет на стороне сервера. Однако данный пункт ломает отображение игры. Есть предположение, что настройка роутинга починит данный момент (так как сейчас есть ошибки при гидратации компонентов на страницах отличных от начальной), но это не точно

2023-05-10 14:30 UTC, KateDriga approved these changes
Отличная работа!

2023-05-10 14:30 UTC, KateDriga commented on packages/server/index.ts
>  import dotenv from 'dotenv'
Подключение к базе следует производить после импорта dotenv, т.к. для подключения используются env variables. 
Т.е. сначала должны идти импорт и dotenv.config(), затем уже методы, в которых используются env variables. 
Не уверена, что нужно сейчас это править, т.к. подключение к базе уже сделано в PR с форумом.

2023-05-10 19:45 UTC, Erebuz approved these changes
Вроде все хорошо. Пара моментов, но это скорее вопросы, а не исправления.

2023-05-10 19:45 UTC, Erebuz commented on packages/client/ssr.tsx
> +import React from 'react'
А React тут в каких-то определенных целях импортируется без использования?

2023-05-10 19:45 UTC, Erebuz commented on packages/server/package.json
> +    "build": "rm -rf dist && tsc --p ./tsconfig.prod.json",
Удаление обязательное? "rm" - команда линукса, на виндовс будет ошибка.

2023-05-14 16:04 UTC, SerghAl commented on packages/client/ssr.tsx
> +import React from 'react'
Да, возникала ошибка, если явный импорт не сделать

2023-05-14 18:19 UTC, SerghAl commented on packages/server/index.ts
>  import dotenv from 'dotenv'
Понял, тогда учту при слиянии

2023-05-14 18:23 UTC, SerghAl commented on packages/server/package.json
> +    "build": "rm -rf dist && tsc --p ./tsconfig.prod.json",
Да, иначе ошибка при сборке выходит. Я запускал через git bash тоже под Windows, поэтому не придал значение

2023-05-16 11:08 UTC, Tsvetkraft requested changes

2023-05-16 11:08 UTC, Tsvetkraft commented on packages/client/src/pages/GamePage/GamePage.tsx
> +  if (typeof window !== 'undefined') {
Когда повторяется трижды, я бы вынес в глобальный метод `typeof window !== 'undefined`

`if (isClientSide())`

2023-05-24 12:28 UTC, Tsvetkraft approved these changes

2023-05-30 07:58 UTC, merged