KVA-38 Sprint 7 ssr router redux
YP-KVAS/Rover-game pull request #28
Opened 2023-05-11 15:40 UTC by KateDriga

### Какую задачу решаем
Настроить Redux и Router в SSR.

### Описание
1. Инициализацию картинок перенесла из файла `game-engine/game-images.ts` в отдельный класс `game-engine/GameImages.ts` (синглтон), т.к. на сервере нет Image и возникали ошибки. Также добавила проверку, что все картинки загружены (иначе, в случае медленного интернета, возникали ситуации, когда на игровом поле часть изображений отсутствовала). Проверка на странице с игрой, т.к. страница старта игры уже удалена [в этом PR](https://github.com/YP-KVAS/Rover-game/pull/27).

2. Добавила проксирование запросов на апи практикума

3. Файл `index.ts` в пакете с сервером довольно большой, часть кода для удобства перенесла в `start-server-helper.ts`

4. Настроила роутинг (для сервера используется StaticRouter)

5. Настроила Redux в SSR (использовала подход с сервисом и репозиторием из [этого](https://youtu.be/G-HHcOwNjZs?t=2060) вебинара)

2023-05-11 22:21 UTC, Erebuz approved these changes
Насколько я вижу, все отлично - даже серверные запросы реализованы. Единственный момент отметил, но может быть, я просто не понял где происходит защита от инъекций.

2023-05-11 22:21 UTC, Erebuz commented on packages/server/index.ts
> +      )}</script>`
Кажется, где-то здесь не хватает защиты от инъекций. 
Я не пытался внедрить что-то по полному пути, но при вызове loader из Route, в initialState попадает инфа с сервера, в которой может содержаться инъекция, которая будет передана сюда, и в итоге - к клиенту.

2023-05-12 10:05 UTC, KateDriga commented on packages/server/index.ts
> +      )}</script>`
Я делала по [документации redux](https://redux.js.org/usage/server-rendering#security-considerations)
Они советуют либо просто escaping открывающегося тега через `replace(/</g, '\\u003c')`, либо использовать библиотеку `serialize-javascript`. Я выбрала второй вариант, больше проверок, возможно она еще пригодится.

2023-05-15 22:40 UTC, Tsvetkraft requested changes
Отличная работа, работа с картинками структурирована просто прекрасно. Ряд мелких комментариев.

2023-05-15 22:40 UTC, Tsvetkraft commented on packages/client/src/App.tsx
> +const mapRoutes = (routes: Array<IRoute>) => {
Не настаиваю, но я бы рассмотрел возможность назвать этот метод `mapRoutesRecursive`. Аргумент за – это облегчает его восприятие, аргумент против – это раскрытие деталей его реализации.

2023-05-15 22:40 UTC, Tsvetkraft commented on packages/client/src/components/LeaderboardTable/LeaderboardTable.tsx
> +    const name =
Оно наверное не к этому изменению, но что-то много разнобоя в том, где может лежать логин и имя пользователя.

2023-05-15 22:40 UTC, Tsvetkraft commented on packages/client/src/game-engine/GameImages.ts
> +    foo: React.Dispatch<React.SetStateAction<boolean>>
не уверен насчёт названия, я бы назвал это handler, например, а не foo

2023-05-15 22:40 UTC, Tsvetkraft commented on packages/client/src/game-engine/game-objects/Rover.ts
>  export class Rover extends DynamicGameCharacter {
Тут, как и везде, я продолжаю сетовать  на нестрелочные методы в классе. Понимаю, что пока что это вас ни за что не кусает, но однажды обязательно укусит.

2023-05-16 08:13 UTC, KateDriga commented on packages/client/src/App.tsx
> +const mapRoutes = (routes: Array<IRoute>) => {
Метод переименовала, так действительно сразу понятно, как он работает.

2023-05-16 08:15 UTC, KateDriga commented on packages/client/src/components/LeaderboardTable/LeaderboardTable.tsx
> +    const name =
Да, данный код я не трогала, для таблицы лидерборда я правила только базовый URL, поскольку теперь проксируем запросы к API практикума, а также удалила неиспользуемые импорты. Видимо до этого кто-то делал коммит, игнорируя прекоммит хук, поэтому автоматически были откорректированы и слишком длинные строки в файле. 

API лидерборда еще в работе, данный код остался с прошлого спринта, когда выводились данные по всем лидербордам, а там действительно структура очень-очень разная приходит. Спасибо за комментарий, это действительно нужно исправлять. Правки должны быть в рамках другой задачи [Добавить API для лидерборда](https://linear.app/kvas/issue/KVA-40/dobavit-api-dlya-liderborda), для командного лидерборда будет единая структура.

2023-05-16 08:17 UTC, KateDriga commented on packages/client/src/game-engine/GameImages.ts
> +    foo: React.Dispatch<React.SetStateAction<boolean>>
Названия откорректировала

2023-05-25 06:37 UTC, merged